# Generated by Django 3.1.4 on 2021-01-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], default='Corona', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room'), ('Stock', 'Stock')], max_length=264, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('mildly ill', 'mildly ill'), ('medium ill', 'medium ill'), ('seriously ill', 'seriously ill'), ('dying', 'dying')], max_length=200, null=True)),
                ('need_ven', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, null=True)),
                ('choice', models.CharField(choices=[('General', 'General'), ('Usage of equipment', 'Usage of equipment'), ('Amount of equipment', 'Amount of equipment'), ('Treatment', 'Treatment'), ('Amount of patient', 'Amount of patient')], max_length=264, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=264, null=True)),
                ('description', models.TextField(max_length=264, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, null=True)),
                ('request', models.CharField(choices=[('Add Equipment', 'Add Equipment'), ('Add Beds', 'Add Beds')], max_length=264, null=True)),
                ('description', models.TextField(max_length=264, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_number', models.IntegerField(null=True)),
                ('ventilator_number', models.IntegerField(null=True)),
            ],
        ),
    ]
