# Generated by Django 3.1.4 on 2021-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='department',
            field=models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='department',
            field=models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=200, null=True),
        ),
    ]
