# Generated by Django 3.1.4 on 2021-01-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('Amount of patient', 'Amount of patient'), ('Amount of equipment', 'Amount of equipment'), ('General', 'General'), ('Usage of equipment', 'Usage of equipment'), ('Treatment', 'Treatment')], max_length=264, null=True),
        ),
    ]
