# Generated by Django 3.1.4 on 2021-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room'), ('Stock', 'Stock')], max_length=264, null=True)),
            ],
        ),
    ]
