# Generated by Django 3.1.4 on 2021-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210109_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('Amount of equipment', 'Amount of equipment'), ('General', 'General'), ('Treatment', 'Treatment'), ('Usage of equipment', 'Usage of equipment'), ('Amount of patient', 'Amount of patient')], max_length=264, null=True),
        ),
    ]
