# Generated by Django 3.1.4 on 2021-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210106_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
