# Generated by Django 3.1.4 on 2021-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_requestform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='name_of_req',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='requestform',
            name='description',
            field=models.TextField(max_length=264, null=True),
        ),
    ]
