# Generated by Django 3.1.4 on 2021-01-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210107_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requestform',
            name='request',
            field=models.CharField(choices=[('Add Beds', 'Add Beds'), ('Add Equipment', 'Add Equipment')], max_length=264, null=True),
        ),
    ]
