# Generated by Django 3.1.4 on 2021-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210108_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentration',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], default='Corona', max_length=200, null=True),
        ),
    ]
