# Generated by Django 3.1.4 on 2021-01-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210108_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, null=True)),
                ('choice', models.CharField(choices=[('Amount of patient', 'Amount of patient'), ('General', 'General'), ('Amount of equipment', 'Amount of equipment')], max_length=264, null=True)),
                ('department', models.CharField(choices=[('Corona', 'Corona'), ('ENP', 'ENP'), ('Heart', 'Heart'), ('Emergency room', 'Emergency room')], max_length=264, null=True)),
                ('description', models.TextField(max_length=264, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
