# Generated by Django 3.1.4 on 2021-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reportform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('Amount of equipment', 'Amount of equipment'), ('Usage of equipment', 'Usage of equipment'), ('Amount of patient', 'Amount of patient'), ('General', 'General')], max_length=264, null=True),
        ),
    ]
