# Generated by Django 3.1.4 on 2021-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('General', 'General'), ('Amount of equipment', 'Amount of equipment'), ('Amount of patient', 'Amount of patient'), ('Treatment', 'Treatment'), ('Usage of equipment', 'Usage of equipment')], max_length=264, null=True),
        ),
    ]
