# Generated by Django 3.1.4 on 2021-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210108_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('Treatment', 'Treatment'), ('General', 'General'), ('Amount of patient', 'Amount of patient'), ('Usage of equipment', 'Usage of equipment'), ('Amount of equipment', 'Amount of equipment')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='request',
            field=models.CharField(choices=[('Add Equipment', 'Add Equipment'), ('Add Beds', 'Add Beds')], max_length=264, null=True),
        ),
    ]
