# Generated by Django 3.1.4 on 2021-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210108_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='choice',
            field=models.CharField(choices=[('Amount of patient', 'Amount of patient'), ('Amount of equipment', 'Amount of equipment'), ('General', 'General'), ('Treatment', 'Treatment'), ('Usage of equipment', 'Usage of equipment')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='request',
            field=models.CharField(choices=[('Add Beds', 'Add Beds'), ('Add Equipment', 'Add Equipment')], max_length=264, null=True),
        ),
    ]
